"""
Razorpay webhook and payment verification HTTP router.

Provides endpoints for Razorpay server-to-server webhook callbacks and client-side
signature verification to complete the full end-to-end payment lifecycle.
"""
import json
import logging
import os
from typing import Optional
from fastapi import APIRouter, Header, HTTPException, Request, status
from pydantic import BaseModel, Field

from app.audit import audit_store
from app.payment.razorpay_client import verify_payment_signature, verify_webhook_signature

logger = logging.getLogger("gateway.payment.router")
router = APIRouter(prefix="/payment", tags=["payment"])


def get_webhook_secret() -> str:
    """Retrieve Razorpay webhook secret from environment."""
    return os.environ.get("RAZORPAY_WEBHOOK_SECRET", "dev-webhook-secret")


class PaymentVerificationRequest(BaseModel):
    """Payload for client-side payment signature verification."""
    razorpay_order_id: str = Field(..., description="Razorpay order ID")
    razorpay_payment_id: str = Field(..., description="Razorpay payment ID returned after checkout")
    razorpay_signature: str = Field(..., description="HMAC-SHA256 signature returned by Razorpay Checkout")


@router.post(
    "/verify",
    status_code=status.HTTP_200_OK,
    summary="Verify client-side Razorpay checkout signature",
)
def verify_payment(payload: PaymentVerificationRequest):
    """
    Verifies the HMAC-SHA256 signature generated by Razorpay Checkout upon successful customer payment.
    """
    is_valid = verify_payment_signature(
        razorpay_order_id=payload.razorpay_order_id,
        razorpay_payment_id=payload.razorpay_payment_id,
        razorpay_signature=payload.razorpay_signature,
    )
    if not is_valid:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid Razorpay payment signature",
        )
    return {
        "verified": True,
        "razorpay_order_id": payload.razorpay_order_id,
        "razorpay_payment_id": payload.razorpay_payment_id,
    }


@router.post(
    "/webhook",
    status_code=status.HTTP_200_OK,
    summary="Receive and verify Razorpay webhook events",
)
async def razorpay_webhook(
    request: Request,
    x_razorpay_signature: Optional[str] = Header(None, alias="X-Razorpay-Signature"),
):
    """
    Processes incoming Razorpay webhook events (e.g. payment.captured, order.paid, payment.failed).
    Verifies HMAC-SHA256 signature, updates the audit event ledger, and finalizes transaction status.
    """
    body_bytes = await request.body()
    webhook_secret = get_webhook_secret()

    # Verify signature
    if not x_razorpay_signature or not verify_webhook_signature(body_bytes, x_razorpay_signature, webhook_secret):
        logger.warning("Rejected webhook: invalid or missing X-Razorpay-Signature")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid webhook signature",
        )

    try:
        data = json.loads(body_bytes.decode("utf-8"))
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid JSON payload",
        )

    event = data.get("event", "")
    entity = (
        data.get("payload", {})
        .get("payment", {})
        .get("entity", {})
    )
    if not entity:
        entity = (
            data.get("payload", {})
            .get("order", {})
            .get("entity", {})
        )

    order_id = entity.get("order_id") or entity.get("id")
    notes = entity.get("notes", {})
    transaction_id = notes.get("transaction_id")

    logger.info("Received Razorpay webhook event: %s for order: %s", event, order_id)

    if transaction_id:
        if event in ("payment.captured", "order.paid"):
            audit_store.update_payment_outcome(
                transaction_id=transaction_id,
                payment_status="captured",
                razorpay_order_id=order_id,
            )
        elif event == "payment.failed":
            audit_store.update_payment_outcome(
                transaction_id=transaction_id,
                payment_status="failed",
                razorpay_order_id=order_id,
            )

    return {
        "status": "ok",
        "event": event,
        "order_id": order_id,
        "processed": bool(transaction_id),
    }
