"""
Razorpay webhook and payment verification HTTP router.

Provides endpoints for Razorpay server-to-server webhook callbacks and client-side
signature verification to complete the full end-to-end payment lifecycle.
"""
import json
import logging
import os
from typing import Optional, Set
from fastapi import APIRouter, Depends, Header, HTTPException, Request, status
from pydantic import BaseModel, Field

from app.audit import audit_store
from app.auth import verify_admin_key
from app.catalog.service import restore_stock
from app.payment.razorpay_client import verify_payment_signature, verify_webhook_signature

logger = logging.getLogger("gateway.payment.router")
router = APIRouter(prefix="/payment", tags=["payment"])

# In-memory deduplication cache for webhook event IDs (idempotency guard)
_processed_webhook_event_ids: Set[str] = set()


def get_webhook_secret() -> str:
    """Retrieve Razorpay webhook secret from environment."""
    return os.environ.get("RAZORPAY_WEBHOOK_SECRET", "dev-webhook-secret")


from uuid import uuid4


class CreateOrderRequest(BaseModel):
    """Payload to create an official Razorpay order for client checkout."""
    receipt: str = Field(..., description="Authorized transaction receipt / UUID")
    amount: Optional[float] = Field(None, description="Amount in INR (must match server record)")
    product_name: Optional[str] = Field(None, description="Product Name")
    customer_id: Optional[str] = Field(None, description="Customer ID")
    checkout_token: Optional[str] = Field(None, description="HMAC authorization token generated by gateway")


@router.post(
    "/create-order",
    status_code=status.HTTP_200_OK,
    summary="Create a real Razorpay Order for client checkout",
)
def create_checkout_order(payload: CreateOrderRequest):
    """
    Creates an official Razorpay Order for frontend client checkout.
    
    Security & Integrity Enforcement:
    1. Requires a valid transaction `receipt` referencing a pre-existing server-side audit transaction
       OR a cryptographically verified `checkout_token`.
    2. Enforces amount matching against server-authorized record to prevent client tampering.
    3. Rejects order creation if the transaction is already captured or settled.
    """
    clean_receipt = (payload.receipt or "").strip()
    if not clean_receipt:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Transaction receipt is required to create a checkout order."
        )

    # 1. Verify existence of server-side transaction record
    record = audit_store.get(clean_receipt)

    from app.payment.service import verify_checkout_token
    token_valid = False
    if payload.checkout_token and payload.amount is not None and payload.customer_id is not None:
        token_valid = verify_checkout_token(
            token=payload.checkout_token,
            receipt=clean_receipt,
            amount_inr=payload.amount,
            customer_id=payload.customer_id,
        )

    if not record and not token_valid:
        logger.warning("Rejected checkout order creation: unauthorized receipt '%s'", clean_receipt)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Unauthorized checkout intent: No corresponding transaction record found for receipt."
        )

    # 2. Check if already settled
    if record and record.payment_status in ("captured", "paid"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Transaction has already been paid and settled."
        )

    # 3. Authoritative amount enforcement (server-grounded)
    if record:
        if payload.amount is not None and abs(payload.amount - record.amount) > 0.01:
            logger.warning(
                "Amount tampering detected for receipt %s: payload ₹%.2f vs authorized ₹%.2f",
                clean_receipt,
                payload.amount,
                record.amount,
            )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Amount mismatch: caller-requested ₹{payload.amount:.2f} does not match server-authorized ₹{record.amount:.2f}."
            )
        authoritative_amount = record.amount
        customer_id = record.customer_id
        product_name = payload.product_name or record.product_id
    else:
        authoritative_amount = payload.amount
        customer_id = payload.customer_id or "CUST001"
        product_name = payload.product_name or "Custom Purchase"

    amount_paise = int(round(authoritative_amount * 100))
    notes = {
        "transaction_id": clean_receipt,
        "product_name": product_name,
        "customer_id": customer_id,
    }
    key_id = os.environ.get("RAZORPAY_KEY_ID", "rzp_test_51tPkUG58N7Lkg")

    try:
        from app.payment.razorpay_client import create_order
        res = create_order(amount_paise=amount_paise, receipt=clean_receipt, notes=notes)
        order_id = res.get("id")

        # Update audit ledger with minted Razorpay order ID and pending status
        if record:
            audit_store.update_payment_outcome(
                transaction_id=clean_receipt,
                payment_status="created",
                razorpay_order_id=order_id,
            )

        return {
            "order_id": order_id,
            "amount": authoritative_amount,
            "currency": "INR",
            "key_id": key_id,
        }
    except Exception as e:
        logger.warning("Could not create Razorpay order for checkout: %s", e)
        if record:
            audit_store.update_payment_outcome(
                transaction_id=clean_receipt,
                payment_status="failed",
            )
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Razorpay order creation failed: {str(e)}",
        )


class PaymentVerificationRequest(BaseModel):
    """Payload for client-side payment signature verification."""
    razorpay_order_id: str = Field(..., description="Razorpay order ID")
    razorpay_payment_id: str = Field(..., description="Razorpay payment ID returned after checkout")
    razorpay_signature: str = Field(..., description="HMAC-SHA256 signature returned by Razorpay Checkout")
    receipt: Optional[str] = Field(None, description="Internal transaction receipt / ID")


@router.post(
    "/verify",
    status_code=status.HTTP_200_OK,
    summary="Verify client-side Razorpay checkout signature",
)
def verify_payment(payload: PaymentVerificationRequest):
    """
    Verifies the HMAC-SHA256 signature generated by Razorpay Checkout upon successful customer payment.
    Updates the ledger state from pending to captured when signature verification succeeds.
    """
    is_valid = verify_payment_signature(
        razorpay_order_id=payload.razorpay_order_id,
        razorpay_payment_id=payload.razorpay_payment_id,
        razorpay_signature=payload.razorpay_signature,
    )
    if not is_valid:
        logger.warning(
            "Rejected invalid Razorpay signature: order_id=%s, payment_id=%s",
            payload.razorpay_order_id,
            payload.razorpay_payment_id,
        )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid Razorpay payment signature: HMAC-SHA256 verification failed",
        )

    # If transaction receipt exists, transition state to captured/settled with strict order-to-receipt binding
    if payload.receipt:
        record = audit_store.get(payload.receipt)
        if not record:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Transaction receipt '{payload.receipt}' not found in audit ledger.",
            )

        # Payment Integrity Guard: enforce order ID binding if previously recorded
        if record.razorpay_order_id and record.razorpay_order_id != payload.razorpay_order_id:
            logger.warning(
                "Payment integrity violation: receipt %s is bound to order %s, but payload submitted %s",
                payload.receipt,
                record.razorpay_order_id,
                payload.razorpay_order_id,
            )
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    f"Payment integrity violation: Submitted order_id '{payload.razorpay_order_id}' "
                    f"does not match bound order '{record.razorpay_order_id}' for receipt '{payload.receipt}'."
                ),
            )

        audit_store.update_payment_outcome(
            transaction_id=payload.receipt,
            payment_status="captured",
            razorpay_order_id=payload.razorpay_order_id or payload.razorpay_payment_id,
            razorpay_payment_id=payload.razorpay_payment_id,
        )
        # If the original proposal was REJECTED/escalated to checkout, mark APPROVED now that payment is captured
        if record.decision == "REJECTED":
            with audit_store._get_connection() as conn:
                conn.cursor().execute(
                    "UPDATE audit_records SET decision = 'APPROVED', decision_reason = ? WHERE transaction_id = ?",
                    (
                        f"Escalated purchase completed via hosted checkout signature verification ({payload.razorpay_payment_id})",
                        payload.receipt,
                    ),
                )
                conn.commit()

    return {
        "verified": True,
        "razorpay_order_id": payload.razorpay_order_id,
        "razorpay_payment_id": payload.razorpay_payment_id,
    }


@router.post(
    "/webhook",
    status_code=status.HTTP_200_OK,
    summary="Receive and verify Razorpay webhook events",
)
async def razorpay_webhook(
    request: Request,
    x_razorpay_signature: Optional[str] = Header(None, alias="X-Razorpay-Signature"),
    x_razorpay_event_id: Optional[str] = Header(None, alias="X-Razorpay-Event-Id"),
):
    """
    Processes incoming Razorpay webhook events (e.g. payment.captured, order.paid, payment.failed).
    Verifies HMAC-SHA256 signature, ensures event deduplication (idempotency), updates the audit event ledger,
    and compensates inventory on payment failure.
    """
    body_bytes = await request.body()
    webhook_secret = get_webhook_secret()

    # 1. Verify signature
    if not x_razorpay_signature or not verify_webhook_signature(body_bytes, x_razorpay_signature, webhook_secret):
        logger.warning("Rejected webhook: invalid or missing X-Razorpay-Signature")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid webhook signature",
        )

    # 2. Parse payload
    try:
        data = json.loads(body_bytes.decode("utf-8"))
    except Exception:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid JSON payload",
        )

    event = data.get("event", "")
    payload_obj = data.get("payload", {})
    
    # Resolve entity across payment, payment_link, and order payload structures
    entity = (
        payload_obj.get("payment", {}).get("entity", {})
        or payload_obj.get("payment_link", {}).get("entity", {})
        or payload_obj.get("order", {}).get("entity", {})
    )

    order_id = entity.get("order_id") or entity.get("id")
    notes = entity.get("notes", {}) or {}
    transaction_id = (
        notes.get("transaction_id")
        or notes.get("receipt")
        or entity.get("reference_id")
        or entity.get("receipt")
    )

    # Check payment_link sub-entity if not found on root entity
    if not transaction_id and "payment_link" in payload_obj:
        plink_entity = payload_obj.get("payment_link", {}).get("entity", {})
        transaction_id = (
            plink_entity.get("reference_id")
            or plink_entity.get("notes", {}).get("transaction_id")
        )

    # 3. Persistent Deduplication Check (Database Idempotency Guard)
    event_id = (
        x_razorpay_event_id
        or data.get("event_id")
        or data.get("id")
        or f"{event}:{order_id}:{entity.get('id', '')}"
    )

    if audit_store.is_webhook_processed(event_id) or event_id in _processed_webhook_event_ids:
        logger.info("Duplicate webhook event %s received — returning deduplicated 200 OK", event_id)
        return {
            "status": "ok",
            "event": event,
            "order_id": order_id,
            "processed": True,
            "deduplicated": True,
        }

    # Persist in DB and memory
    audit_store.record_webhook_event(event_id)
    _processed_webhook_event_ids.add(event_id)
    logger.info("Received and processing Razorpay webhook event: %s (id: %s) for order: %s, tx: %s", event, event_id, order_id, transaction_id)

    # 4. State Transitions and Inventory Compensation
    if transaction_id:
        record = audit_store.get(transaction_id)
        if record:
            if event in ("payment.captured", "order.paid", "payment_link.paid"):
                webhook_payment_id = (
                    payload_obj.get("payment", {}).get("entity", {}).get("id")
                    or (entity.get("id") if str(entity.get("id", "")).startswith("pay_") else None)
                )
                audit_store.update_payment_outcome(
                    transaction_id=transaction_id,
                    payment_status="captured",
                    razorpay_order_id=order_id,
                    razorpay_payment_id=webhook_payment_id,
                )
                if record.decision == "REJECTED":
                    with audit_store._get_connection() as conn:
                        conn.cursor().execute(
                            "UPDATE audit_records SET decision = 'APPROVED', decision_reason = ? WHERE transaction_id = ?",
                            (f"Escalated purchase completed via Razorpay webhook ({event})", transaction_id),
                        )
                        conn.commit()
            elif event in ("payment.failed", "payment_link.cancelled", "payment_link.expired"):
                # Automated inventory compensation: restore decremented stock
                restore_stock(record.product_id, record.quantity)
                logger.info("Restored %s units of %s after %s event", record.quantity, record.product_id, event)

                audit_store.update_payment_outcome(
                    transaction_id=transaction_id,
                    payment_status="failed",
                    razorpay_order_id=order_id,
                )
        else:
            logger.warning("Webhook received for unknown or untracked transaction: %s", transaction_id)

    return {
        "status": "ok",
        "event": event,
        "order_id": order_id,
        "processed": bool(transaction_id and audit_store.get(transaction_id)),
        "deduplicated": False,
    }


class SimulateWebhookRequest(BaseModel):
    """Payload to simulate Razorpay webhook execution in test/sandbox mode."""
    transaction_id: str = Field(..., description="Transaction UUID to settle")
    event: Optional[str] = Field("payment.captured", description="Razorpay webhook event type")


@router.post(
    "/simulate-webhook",
    status_code=status.HTTP_200_OK,
    summary="Simulate incoming Razorpay webhook for test-mode settlement",
    dependencies=[Depends(verify_admin_key)],
)
def simulate_webhook(payload: SimulateWebhookRequest):
    """
    Test-mode endpoint simulating an authoritative Razorpay webhook (e.g. payment.captured).
    Transitions the transaction in the audit ledger from PENDING to CAPTURED.
    Requires Admin API Key authentication and environment guard (disabled in production unless DEMO_MODE=true).
    """
    env = os.environ.get("ENVIRONMENT", "development").lower()
    demo_mode = os.environ.get("DEMO_MODE", "true").lower()
    if env == "production" and demo_mode != "true":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Webhook simulation is disabled in production environments.",
        )
    clean_tx = payload.transaction_id.strip()
    record = audit_store.get(clean_tx)
    if not record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Transaction '{clean_tx}' not found in audit ledger.",
        )

    order_id = record.razorpay_order_id or f"order_{clean_tx.replace('-', '')[:14]}"
    payment_id = f"pay_sim_{uuid4().hex[:12]}"

    audit_store.update_payment_outcome(
        transaction_id=clean_tx,
        payment_status="captured",
        razorpay_order_id=order_id,
        razorpay_payment_id=payment_id,
    )

    if record.decision == "REJECTED":
        with audit_store._get_connection() as conn:
            conn.cursor().execute(
                "UPDATE audit_records SET decision = 'APPROVED', decision_reason = ? WHERE transaction_id = ?",
                (
                    f"Escalated purchase completed via simulated Razorpay webhook ({payload.event} - {payment_id})",
                    clean_tx,
                ),
            )
            conn.commit()

    return {
        "status": "ok",
        "event": payload.event,
        "transaction_id": clean_tx,
        "payment_id": payment_id,
        "order_id": order_id,
        "payment_status": "captured",
        "settled": True,
    }
